package greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table SCAN.
 */
public class Scan {

    private Long id;
    private String NetID;
    private Integer Attendance;
    private String ScanTime;
    private String ScanDate;
    private Integer Week;

    public Scan() {
    }

    public Scan(Long id) {
        this.id = id;
    }

    public Scan(Long id, String NetID, Integer Attendance, String ScanTime, String ScanDate, Integer Week) {
        this.id = id;
        this.NetID = NetID;
        this.Attendance = Attendance;
        this.ScanTime = ScanTime;
        this.ScanDate = ScanDate;
        this.Week = Week;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getNetID() {
        return NetID;
    }

    public void setNetID(String NetID) {
        this.NetID = NetID;
    }

    public Integer getAttendance() {
        return Attendance;
    }

    public void setAttendance(Integer Attendance) {
        this.Attendance = Attendance;
    }

    public String getScanTime() {
        return ScanTime;
    }

    public void setScanTime(String ScanTime) {
        this.ScanTime = ScanTime;
    }

    public String getScanDate() {
        return ScanDate;
    }

    public void setScanDate(String ScanDate) {
        this.ScanDate = ScanDate;
    }

    public Integer getWeek() {
        return Week;
    }

    public void setWeek(Integer Week) {
        this.Week = Week;
    }

}
